Repository multacc/multacc, pull requests merged in 2020-03, with the labels that each got.

#17 Add fromJson and toJson to MultaccItem, allowing storage of arbitrary data
  lib/contact_types/twitter.dart
  lib/items/item.dart
  lib/items/twitter.dart
  lib/pages/contacts/contact_model.dart
Labels: P2, frontend-logic, local-database

#23 Add navigation, new theme, logo, contact details page
  .gitignore
  README.md
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/drawable-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/drawable-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/drawable-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/drawable-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/drawable-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-anydpi-v26/launcher_icon.xml
  android/app/src/main/res/mipmap-hdpi/launcher_icon.png
  android/app/src/main/res/mipmap-mdpi/launcher_icon.png
  android/app/src/main/res/mipmap-xhdpi/launcher_icon.png
  android/app/src/main/res/mipmap-xxhdpi/launcher_icon.png
  android/app/src/main/res/mipmap-xxxhdpi/launcher_icon.png
  android/app/src/main/res/values/colors.xml
  assets/icon.png
  assets/logo.png
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/contents.xcworkspacedata
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-50x50@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-50x50@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-72x72@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-72x72@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  lib/common/constants.dart
  lib/common/routes.dart
  lib/main.dart
  lib/pages/chats/chats_page.dart
  lib/pages/contacts/contact_card.dart
  lib/pages/contacts/contact_details_page.dart
  lib/pages/contacts/contact_shortcut.dart
  lib/pages/contacts/contacts_data.dart
  lib/pages/contacts/contacts_page.dart
  lib/pages/home_page.dart
  lib/pages/profile/profile_page.dart
  lib/pages/settings/settings_page.dart
  pubspec.yaml
Labels: P1

#32 Convert email and phone to MultaccItem
  lib/items/email.dart
  lib/items/item.dart
  lib/items/phone.dart
  lib/items/twitter.dart
  lib/pages/contacts/contact_model.dart
  pubspec.yaml
Labels: P1, frontend-logic

#42 Add google signin, chats screen, groupme chats
  .github/config.yml
  .github/workflows/main.yml
  .gitignore
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/modules.xml
  .idea/runConfigurations/main_dart.xml
  .idea/vcs.xml
  android/app/build.gradle
  android/build.gradle
  android/multacc_android.iml
  assets/groupme.svg
  lib/common/bottom_bar.dart
  lib/common/constants.dart
  lib/common/draggable_sheet_widget.dart
  lib/main.dart
  lib/pages/chats/chat_model.dart
  lib/pages/chats/chats_data.dart
  lib/pages/chats/chats_page.dart
  lib/pages/contacts/contacts_page.dart
  lib/pages/home_page.dart
  multacc.iml
  pubspec.yaml
Labels: P1, enhancement, frontend-design, frontend-logic

#48 Add MultaccItem type to JSON representation
  lib/items/email.dart
  lib/items/item.dart
  lib/items/phone.dart
  lib/items/twitter.dart
Labels: P1, local-database

#51 Use enum value name instead of index in json
  lib/items/email.dart
  lib/items/item.dart
  lib/items/phone.dart
  lib/items/twitter.dart
  pubspec.yaml
Labels: P1, frontend-logic, local-database

#56 Local db
  lib/database/database_interface.dart
  lib/items/email.dart
  lib/items/phone.dart
  lib/main.dart
  lib/pages/contacts/contacts_data.dart
  pubspec.yaml
Labels: P1, local-database

#57 Improve contact details page
  android/app/build.gradle
  lib/common/avatars.dart
  lib/common/bottom_bar.dart
  lib/common/constants.dart
  lib/common/draggable_sheet_widget.dart
  lib/common/search_delegate.dart
  lib/common/theme.dart
  lib/items/email.dart
  lib/items/item.dart
  lib/items/phone.dart
  lib/items/twitter.dart
  lib/main.dart
  lib/pages/chats/chats_data.dart
  lib/pages/chats/chats_page.dart
  lib/pages/contacts/contact_details_page.dart
  lib/pages/contacts/contact_model.dart
  lib/pages/contacts/contact_shortcut.dart
  lib/pages/contacts/contacts_page.dart
  lib/pages/home_page.dart
  lib/pages/settings/settings_page.dart
  pubspec.yaml
Labels: P2, frontend-design, frontend-logic

#61 Fix failing build from #56
  lib/database/database_interface.dart
  lib/main.dart
Labels: P1

#72 Store additional MultaccContact fields in database
  lib/database/database_interface.dart
  lib/database/type_ids.dart
  lib/items/item.dart
  lib/main.dart
  lib/pages/contacts/contact_model.dart
  lib/pages/contacts/contacts_data.dart
Labels: P1, local-database

#123 Register Hive adapters
  lib/database/database_interface.dart
Labels: P1, local-database

#125 Item model updates for edit & connect support
  lib/items/email.dart
  lib/items/item.dart
  lib/items/phone.dart
  lib/items/twitter.dart
  lib/pages/contacts/contact_details_page.dart
  pubspec.yaml
Labels: frontend-logic

#136 Fix permissions handler syntax
  lib/main.dart
Labels: P1, bug
