Repository multacc/multacc, pull requests merged in 2020-04, with the labels that each got.

#137 Add support for skipping sign in
  lib/common/bottom_bar.dart
  lib/pages/home_page.dart
Labels: P2

#139 Unit tests for sprint-2
  lib/items/email.dart
  pubspec.yaml
  test/items/email_test.dart
  test/items/item_test.dart
Labels: P1, frontend-logic

#138 Add Auth class to wrap FirebaseAuth, allowing google sign in from anywhere in app
  lib/common/auth.dart
  lib/common/bottom_bar.dart
  lib/pages/home_page.dart
Labels: P3, frontend-logic

#143 Add messages screen
  lib/common/search_delegate.dart
  lib/common/theme.dart
  lib/main.dart
  lib/pages/chats/chat_model.dart
  lib/pages/chats/chats_data.dart
  lib/pages/chats/chats_page.dart
  lib/pages/chats/messages_page.dart
  lib/pages/contacts/contact_details_page.dart
  lib/pages/home_page.dart
  lib/pages/settings/settings_page.dart
  pubspec.yaml
Labels: P3

#166 Correct build-breaking merge
  lib/items/item.dart
Labels: P1, bug

#175 Refactor contact input fields and base item conversion
  lib/items/email.dart
  lib/items/phone.dart
  lib/items/text.dart
  lib/items/url.dart
  lib/pages/contacts/contact_form_page.dart
  lib/pages/home_page.dart
Labels: P2, frontend-logic

#195 Require Hive 1.4 in pubspec
  pubspec.yaml
Labels: bug

#196 Add `flutter test` to github actions workflow
  .github/workflows/main.yml
  test/items/twitter_test.dart
Labels: P3, bug

#215 Rudimentary contact sharing
  firebase/.gitignore
  firebase/firebase.json
  firebase/functions/.gitignore
  firebase/functions/npm-update-firebase
  firebase/functions/package-lock.json
  firebase/functions/package.json
  firebase/functions/src/index.ts
  firebase/functions/src/schema.ts
  firebase/functions/src/storage.ts
  firebase/functions/src/web.ts
  firebase/functions/tsconfig.json
  firebase/functions/tslint.json
  firebase/public/index.html
  firebase/public/static/style.css
  lib/common/constants.dart
  lib/database/contact_model.dart
  lib/database/database_interface.dart
  lib/items/item.dart
  lib/pages/contacts/contact_details_page.dart
  lib/pages/contacts/contact_form_page.dart
  lib/pages/home_page.dart
  lib/pages/profile/share_page.dart
  lib/sharing/receive.dart
  lib/sharing/send.dart
  pubspec.yaml
  test/items/email_test.dart
  test/items/phone_test.dart
  test/items/twitter_test.dart
Labels: frontend-logic
